### ISSUE TITLE
Create Opinions Page

### ISSUE THREAD

**Issue by moorejah** [moorejah/project#12]
**Persona:**
Edward the Educator

**User Story:**
As an educator, 
Edward wants an effective way to visualize the great power competition between U.S. and China through the lens of shifts in public opinion,
So that he can provide visuals for students to better understand the impact that public opinion can have on edging countries towards conflict.

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of done:** 
- [x] Ed can look at this page and quickly see a visual about the US and China's opinions of each other
- [x] Ed can quickly read about reasons for shifting trends
- [x] Ed can quickly navigate to other site pages if needed

**Tasks:**
- [x] Create opinions page
- [x] Add opinions visualization chart
- [x] Add text describing reasons for trends over time

**Comment by moorejah** [comment]
We need to populate this user story.
