### ISSUE TITLE
Create Military Page

### ISSUE THREAD

**Issue by moorejah** [moorejah/project#2]
**Persona:**
Edward the Educator

**User Story:**
As a Professor of Political Science at the Harvard Kennedy School of Government,
Edward wants an effective way to visualize the great power competition between U.S. and China through the lens of military spending
So that he can provide visuals for students to better understand the impact that military spending can have on edging countries towards conflict.

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of done:** 
- [x] Edward can look at the page and visually see US vs. China military spending over time and reasons for that change

**Tasks**
- [x] Create chart of military spending
- [x] Create list of reasons for increased spending

**Comment by moorejah** [comment]
Hi Team, I've set the users stories up. Once we fill them out then we need to decide whether we want to take them on in Sprint 1 or Sprint 2.
