### ISSUE TITLE
Create CSS Style Sheet

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#20]
**Persona:**
Jennifer

**User Story:**
As a general user, 
Jennifer wants to see site pages that are visually well-organized and styled consistently
So that her eye is drawn to the most important information on the page and she can easily identify different pages as part of the same site

**Invest Criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of done:**
- [x] Jennifer can understand each page is part of the same T-Trap website because all pages have a consistent look and feel
- [x] Jennifer can easily read texts and charts because they are appropriately sized and positioned

**Tasks:**
- [x] create css style sheet for use on all site pages
- [x] define html and body styles (font, font size, color, background color, etc.)
- [x] define sizing and position of images relative to body frame
