### ISSUE TITLE
Create Our Team Page

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#23]
**Persona:** 
Nate the Networker

**User Story:**
Nate is a recruiter for state department jobs who needs to find the best talent and expertise so that he can meet his goals to improve the talent pool for the state department.

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of done:**
- [x] Nate can find out who the creators of the T-trap site are

**Tasks:**
- [x] add names and bio information to the our team page
- [x] link our team page to navigation bar across site
