### ISSUE TITLE
create counterarguments page

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#26]
**Persona:**
Dave the Doubter

**User Story:**
As an individal suspicious of the premise of a US/China T-trap
Dave wants a page to describe the main counterarguments against the idea that the T-trap is happening between the US and China
So that he can find information to present in his class

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of done:**
- [x] Dave has a separate section of the site where he can see counterarguments

**Tasks:**
- [x] create counterargument page
- [x] add main counterarguments
