### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by moorejah** [moorejah/project#3]
**Persona:**
Jennifer the General Reader

**User Story:**
As a general reader, Jennifer wants to know what a Thucydides’ Trap is after it was brought up in a conversation/news story, So that she can quickly grasp what people are talking about next time it comes up.

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of Done:** 
- [x] Jennifer reads first page and can 1) explain who Thucydides was and 2) and explain what the theory means and 3) navigate to other pages if she wants to learn more

**Tasks:** 
- [x] Create paragraphs briefly describing Thucydides’ trap
- [x] Create links to “GDP”, “Military Spending”, and "Opinion Polls" pages

**Comment by moorejah** [comment]
Hi Team, I've set the users stories up. Once we fill them out then we need to decide whether we want to take them on in Sprint 1 or Sprint 2.
