### ISSUE TITLE
Create GDP Page

### ISSUE THREAD

**Issue by moorejah** [moorejah/project#4]
**Persona:**
Samantha the Student

**User Story:**
As a student (e.g., Econ Major),
Samantha wants to understand the great power competition between the U.S. and China through the lens of economic indicators
So that she can add a section to her term paper about geopolitical trends through the lens of the T-trap. 

**INVEST criteria:**
The user story is INDEPENDENT because… it does not depend on any other features to be built before it
The user story is NEGOTIABLE because… it is not an explicit contract for features
The user story is VALUABLE because…. it is valuable to the persona
The user story is ESTIMABLE because… it can be completed in a reasonably estiable amount of time
The user story is SMALL because… it is small enough for a member of our team to complete it within less than two days of work (our team's definition of small given the length of the course)
The user story is TESTABLE because… this persona could easily verify if the intended value is provided

**Definition of Done:** 
- [x] Samantha can quickly read about GDP trends and visualize those trends over time

**Tasks:** 
- [x] create GDP over time page
- [x] add basic information about GDP trends over time for the US and China and how it relates to T-Trap
- [x] Add basic chart of GDP over time for each country

**Comment by moorejah** [comment]
Hi Team, I've set the users stories up. Once we fill them out then we need to decide whether we want to take them on in Sprint 1 or Sprint 2.
