### ISSUE TITLE
add page to describe "soft power competition" between US and China

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#45]
**Persona:**
Samantha

**User Story:**
As a student 
Samantha wants to understand more about "soft power competition" 
so that she can add this to her reserach paper as a contributing factor to the T-trap problem

**Definition of Done:**
- [ ] Samantha can navigate to a separate page where she finds information about soft power competition between the US and China

**Tasks:**
- [ ] create soft power page
- [ ] add graphic and text to describe
- [ ] add sources section to link to sources
- [ ] add to navigation bar on all pages
