### ISSUE TITLE
add PPP GDP information alongside nominal to the GDP page

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#49]
**Persona:**
Samantha

**User Story:**
As an econ student
Samantha want GDP information in both PPP and nominal terms
so that she can be more thorough in her research paper and get an A

**Definition of Done:**
- [ ] Samantha can see both PPP and nominal GDP data on the GDP page

**Tasks:**
- [ ] add PPP data alongside nominal data on GDP page
- [ ] add sources for PPP data
