### ISSUE TITLE
organize repo files into folders / subfolders per class guidelines

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#53]
**Persona:**
Team 4

**User story:**
as a student team
team 4 wants their github repo organized
so that they don't get overwhelmed with too many files in the main folder and can easily find files in subfolders

Definition of done:
- [x] team 4 does not see too many files in the main folder and can easily find other files they need

**Tasks:**
- [x] create folders for data, styles, images, javascript, etc.
- [x] link file paths appropriately in html files
