### ISSUE TITLE
add counterarguments to all content pages - gdp, military, and opinion (Dave)

### ISSUE THREAD

**Issue by smitjuli** [moorejah/project#58]
**Persona:**
Dave

**User Story:**
As a skeptic
Dave wants to see counterarguments specific to each section on the site (gdp, military, etc.)
so he can use this information to more effectively argue against the t-trap premise

**Definition of Done:**
- [ ] Dave can see a section on each content page describing counterarguments to why the evidence presented is not indicative of a t-trap

**Tasks:**
- [ ] add counterargument section specific to each content page
- [ ] remove general counterarguments page
